# Convert str(array) back to numpy array
+ date: 2017-05-21
+ tags: snippet

If we print a numpy array, which actually use `str()`, we will find it almost irreversible.

In [74]:
l=arange(16).reshape(4,4)
print('l is printed as:\n', l)

l is printed as:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Use `print()` will fallback to `str()`, so `str()` is not the correct way. 
+ `repr()`
+ `.tolist()`

In [77]:
print('Array Form:\n', repr(l))
print('List form:\n', l.tolist())

Array Form:
 array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
List form:
 [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]


## Recover your fault
If you really need to convert the array string separated by spaces into python, here is a remedy `str2array()`: 

In [79]:
import re
import ast
def str2array(s):
    s=re.sub('\[ +', '[', s.strip())
    l=ast.literal_eval(re.sub('[\n ]+', ', ', s))
    return array(l)

In [80]:
s=''' [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]'''
str2array(s)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])